- src/app/my-team/page.jsx
- src/components/StudentAccountForm/StudentAccountForm.js
- src/styles/StudentAccountForm.module.css
Basic UI for Student Account Creation
> Account creation

- src/components/StudentAccountForm/StudentAccountForm.js
- src/styles/StudentAccountForm.module.css
> Updated StudentAccountForm.js

- prisma/schema.prisma
- src/app/advisor-directory/layout.jsx
- src/app/faculty-proposals/layout.jsx
- src/app/my-team/layout.jsx
- src/app/my-team/page.jsx
- src/app/page.jsx
- src/app/student-proposals/layout.jsx
- src/components/Navbar/Navbar.jsx
- src/components/StudentAccountForm/StudentAccountForm.jsx
- src/components/protected/Faculty.jsx
- src/components/protected/Student.jsx
- src/components/protected/StudentOrFaculty.jsx
- src/lib/auth.js
- src/middleware.js
- added layouts for protected routes
- fixed logo not showing up
> protected routes

- src/app/proposal-form/page.jsx
- src/components/ProjectProposalForm/Proposal.jsx
- src/styles/ProposalForm.module.css
The project proposal form is built out with all components, but it does not have any styling.
> Proposal form

- src/app/my-team/createaccount/page.jsx
- src/app/my-team/page.jsx
- src/components/ui/button.jsx
- src/styles/StudentAccountForm.module.css
Updated page, put them under my-team, modified routing, and updated button.jsx with custom variation
> Updated Student Account Page

- README.md
> Change licence name in readme

- src/app/my-team/page.jsx
- src/app/my-team/profile.module.css
- src/components/StudentAccountForm.jsx
- src/components/StudentOverview.jsx
- src/components/ui/button.jsx
- src/styles/StudentOverview.module.css
Created the UI for the box with the student overview for SD project
Missing: routing implementation to the different pages and backend information stored in the database
> updated My-Team

- src/app/my-team/page.jsx
- src/app/my-team/profile.module.css
- src/components/Checklist.jsx
- src/components/StudentOverview.jsx
- src/styles/StudentOverview.module.css
created progress bar for the student page, need to still fix ui
> Created Checklist

- src/components/Checklist.jsx
- src/components/StudentOverview.jsx
updated UI of checklist (padding/spacing) and deleted unneccesary code from studentoverview.jsx
> Updated Progress Checklist

- src/lib/server/proposals.js
Created the server action under @lib/server/proposals.js to return a list of m proposed projects starting at the nth index. 
Note: we may want to consider updating to take in optionals to allow for additional filtering of the data
> Created server action to return list of proposals

- package-lock.json
- package.json
- src/app/(faculty)/profile/page.jsx
- src/app/(faculty)/profile/profile.module.css
- src/components/FacultyAccountForm.jsx
- src/components/StudentAccountForm.jsx
- src/styles/FacultyAccountForm.module.css
- created the form and put it under faculty
- also created a page.jsx for the profile navigation 
- need to make Department portion a dropdown, modify padding around profile picture, and fix positioning of camera icon
> Created Faculty Profile Page

- src/app/(auth-user)/proposals/[proposalID]/page.jsx
- src/app/(auth-user)/proposals/page.jsx
- src/components/sidebar/app-sidebar.jsx
- Remove sidebar toggle
- Add "reset filter" button
- Add "Propose your own project" link on proposals page 
- Add "Request to join" on specific project page
> Edit sidebar and proposals pages

- src/app/(auth-user)/advisor-directory/page.jsx
- src/components/sidebar/directory-sidebar.jsx
> basic UI for Faculty directory

- src/components/Checklist.jsx
- src/components/StudentOverview.jsx
- src/styles/StudentOverview.module.css
team formation, merged team formation stuff that I did plus what vlad did
> Updated Team Formation

- src/app/(auth-user)/proposals/page.jsx
- src/components/ProjectProposalForm/Proposal.jsx
- src/components/sidebar/app-sidebar.jsx
- src/lib/server/proposals.js
filters working for proposals page
> Feature/apply filter from UI

- src/app/(auth-user)/requests/page.jsx
- src/components/Navbar/Navbar.jsx
- src/components/Requests.jsx
I created a **separate navigation configuration for faculty members**
The navbar has "project proposals" (same as student view) and "advisor requests."
The navbar component now 
1. retrieves the user role from the session and 
2. renders the appropriate array of links depending on the user's role.
I **created the Advisor Requests page**.
The page has a flex 2-col grid with cards. Each card component has 2 nav tabs that change the card content based on which one is active.
1. Project Overview (default tab): project title and summary
2. Manage: project title, project members, and two buttons
> Faculty pages

- src/app/(auth-user)/my-team/page.jsx
- src/components/Checklist.jsx
- src/components/Overview.jsx
- src/styles/StudentOverview.module.css
- src/styles/profile.module.css
- deleted settings for account on my team page, replacing it with checklist
- modified styling to make ui more cohesive
- added period to a sentence
> Updated Student Overview

- package-lock.json
- package.json
- src/app/(admin)/admin/page.jsx
- src/app/(admin)/super-admin/page.jsx
- src/app/(faculty)/faculty/page.jsx
- src/app/(student)/student/page.jsx
- src/components/ui/accordion.jsx
- tailwind.config.js
- student page: welcome statement, get started, and navigation help
- faculty page: welcome statement, get started, and navigation help
- admin page: welcome statement, get started, navigation help 
- added accordion from Shadcn
------
for faculty, routing in my team and my profile are not working
> Updated Home Pages for Different Views

- package-lock.json
- src/app/(auth-user)/proposals/[proposalID]/page.jsx
- src/app/(auth-user)/proposals/page.jsx
- src/app/api/interested-in/route.js
- src/components/InterestedButton.jsx
- src/lib/server/interested.js
- UI Complete
- May not be running on my machine because of the local migration issue.
> Interested in button: With issue

- package-lock.json
- src/app/(auth-user)/advisor-directory/[advisorID]/page.jsx
- src/app/(auth-user)/archive/[context_key]/page.jsx
- src/app/(auth-user)/archive/page.jsx
- src/app/(auth-user)/proposals/[proposalID]/page.jsx
- src/app/(auth-user)/proposals/page.jsx
- src/app/api/interested-in/route.js
- src/components/InterestedButton.jsx
- src/lib/server/interested.js
- src/lib/server/scholar-commons.js
Title is self explanatory, cleaned up so stuff and also added Dr. Atkinson to faculty table to allow for real testing.
> Added Previous Works Section To Faculty Profile
